name: Deploy Shiny App to shinyapps.io

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("shiny", "dplyr", "tidyverse", "shinythemes", "DT", "shinyWidgets", "scales", "rsconnect"), dependencies=TRUE)'

    - name: Deploy Shiny App to shinyapps.io
      env:
        SHINYAPPSIO_TOKEN: ${{ secrets.SHINYAPPSIO_TOKEN }}
        SHINYAPPSIO_SECRET: ${{ secrets.SHINYAPPSIO_SECRET }}
        SHINYAPPSIO_ACCOUNT: ${{ secrets.SHINYAPPSIO_ACCOUNT }}
      run: |
        Rscript -e "
          library(rsconnect);
          rsconnect::setAccountInfo(
            name=Sys.getenv('SHINYAPPSIO_ACCOUNT'), 
            token=Sys.getenv('SHINYAPPSIO_TOKEN'), 
            secret=Sys.getenv('SHINYAPPSIO_SECRET')
          );
          rsconnect::deployApp(
            appFiles = c('app.R', 'output/transparentcalifornia-outreach.rds'),
            appName = 'your-app-name',
            account = Sys.getenv('SHINYAPPSIO_ACCOUNT'),
            forceUpdate = TRUE
          )
        "
