name: Deploy Shiny App to shinyapps.io

on:
  workflow_dispatch:

jobs:
  deploy_app:
    uses: ./.github/workflows/setup-r-env.yml
    with:
      r-version: 'release' # Or specify a version
      r-packages: "'shiny','dplyr','tidyverse','shinythemes','DT','shinyWidgets','scales','rsconnect'"
      # run-script-path: not needed for this workflow
      # do-git-commit-push: false (default)
      do-shiny-deploy: true
      shiny-app-files: 'app.R output/transparentcalifornia-outreach.rds' # Space separated
      shiny-app-name: 'your-app-name' # Matches original
    secrets:
      shinyappsio-account: ${{ secrets.SHINYAPPSIO_ACCOUNT }}
      shinyappsio-token: ${{ secrets.SHINYAPPSIO_TOKEN }}
      shinyappsio-secret: ${{ secrets.SHINYAPPSIO_SECRET }}
