name: Run TransparentCalifornia Scraper

on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages(c("rvest", "tidyverse", "lubridate", "gmt", "humaniformat"))'

    - name: Run R script
      run: |
        Rscript transparentcalifornia.R
