name: Run TransparentCalifornia Scraper

on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *' # Runs at 00:00 on Jan 1, Apr 1, Jul 1, Oct 1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages("remotes")'
        Rscript -e 'remotes::install_cran(c("rvest", "tidyverse", "lubridate", "gmt", "humaniformat"))'

    - name: Run R script
      run: |
        Rscript transparentcalifornia.R

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Commit and push changes
      run: |
        git add output/transparentcalifornia-outreach.rds
        git commit -m "Update data"
        git push
