name: Run TransparentCalifornia Scraper, Create Data PR, and Deploy Shiny App

on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *' # Quarterly on the 1st day of Jan, Apr, Jul, Oct at midnight
  workflow_dispatch:

jobs:
  scrape_create_pr_and_deploy:
    uses: ./.github/workflows/setup-r-env.yml
    # Permissions required by the reusable workflow for creating branches and PRs
    permissions:
      contents: write
      pull-requests: write
    with:
      r-version: 'release' 
      r-packages: "'httr','xml2','rvest','dplyr','purrr','stringr','readr','tidyr','tibble','lubridate','geosphere','humaniformat','rsconnect'"
      run-script-path: 'transparentcalifornia.R'
      
      # Parameters for creating a Pull Request instead of direct commit
      do-git-create-pr: true
      git-commit-files: 'output/transparentcalifornia-outreach.rds' # Default, but explicit
      git-commit-message: 'Automated data update for TransparentCalifornia' # More specific message
      pr-title: 'Automated Data Update: TransparentCalifornia Outreach Data'
      pr-body: 'This PR contains automated updates to the `output/transparentcalifornia-outreach.rds` file generated by the scraper.'
      pr-base-branch: 'main' # Or your default branch

      # Parameters for Shiny App deployment (deploys from the main branch checkout)
      do-shiny-deploy: true
      shiny-app-files: 'app.R output/transparentcalifornia-outreach.rds' # Space separated
      shiny-app-name: 'your-app-name' 
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }} # Pass the GITHUB_TOKEN for gh CLI and git operations
      shinyappsio-account: ${{ secrets.SHINYAPPSIO_ACCOUNT }}
      shinyappsio-token: ${{ secrets.SHINYAPPSIO_TOKEN }}
      shinyappsio-secret: ${{ secrets.SHINYAPPSIO_SECRET }}
