name: Run TransparentCalifornia Scraper and Deploy Shiny App

on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup R environment
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("httr", "xml2", "rvest", "dplyr", "purrr", "stringr", "readr", "tidyr", "tibble", "lubridate", "geosphere", "humaniformat", "rsconnect"), dependencies=TRUE)'

    - name: Install Bioconductor package Biobase
      run: |
        Rscript -e 'if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")'
        Rscript -e 'BiocManager::install("Biobase")'

    - name: Run TransparentCalifornia Scraper
      run: Rscript transparentcalifornia.R

    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Commit and push updated data
      run: |
        git add output/transparentcalifornia-outreach.rds
        git commit -m "Update underlying data via scraper" || echo "No changes to commit"
        git push
      continue-on-error: true

    - name: Deploy Shiny App to shinyapps.io
      env:
        SHINYAPPSIO_TOKEN: ${{ secrets.SHINYAPPSIO_TOKEN }}
        SHINYAPPSIO_SECRET: ${{ secrets.SHINYAPPSIO_SECRET }}
        SHINYAPPSIO_ACCOUNT: ${{ secrets.SHINYAPPSIO_ACCOUNT }}
      run: |
        Rscript -e "
          library(rsconnect);
          rsconnect::setAccountInfo(
            name = Sys.getenv('SHINYAPPSIO_ACCOUNT'),
            token = Sys.getenv('SHINYAPPSIO_TOKEN'),
            secret = Sys.getenv('SHINYAPPSIO_SECRET')
          );
          rsconnect::deployApp(
            appFiles = c('app.R', 'output/transparentcalifornia-outreach.rds'),
            appName = 'your-app-name',
            account = Sys.getenv('SHINYAPPSIO_ACCOUNT'),
            forceUpdate = TRUE
          )
        "
