name: Run TransparentCalifornia Scraper

on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Changed to ubuntu-latest for better compatibility

    steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages(c("httr", "xml2", "rvest", "tidyverse", "lubridate", "geosphere", "humaniformat"))'

    - name: Print installed packages
      run: Rscript -e 'print(installed.packages()[,c("Package", "Version")])'

    - name: Run R script
      run: Rscript transparentcalifornia.R

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Commit and push changes
      run: |
        git add output/transparentcalifornia-outreach.rds
        git commit -m "Update data"
        git push
