name: Run TransparentCalifornia Scraper

on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies (with retries)
      run: |
          attempt=0
          max_attempts=3
          while [ $attempt -lt $max_attempts ]; do
            Rscript -e 'install.packages("remotes")' && \
            Rscript -e 'remotes::install_cran(c("httr", "xml2", "rvest", "tidyverse", "lubridate", "gmt", "humaniformat"))' && \
            break  # Exit the loop if successful
            attempt=$((attempt+1))
            echo "Installation failed, retrying in 30 seconds (attempt $attempt/$max_attempts)..."
            sleep 30
          done
          if [ $attempt -eq $max_attempts ]; then
            echo "Installation failed after $max_attempts attempts. Exiting with error."
            exit 1
          fi

    - name: Print installed packages
      run: Rscript -e 'print(installed.packages()[,c("Package", "Version")])'

    - name: Run R script
      run: Rscript transparentcalifornia.R

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Commit and push changes
      run: |
        git add output/transparentcalifornia-outreach.rds
        git commit -m "Update data"
        git push
